package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	MaintenanceNotification struct {
		MaintenanceNotification   string      `json:"document_no"`
		Plant                     string      `json:"deliver_to"`
		OrderQuantity             string      `json:"quantity"`
		PickedQuantity            string      `json:"picked_quantity"`
		NetPriceAmount            string      `json:"price"`
	    Batch                     string      `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string      `json:"document_no"`
		Status               string      `json:"status"`
		DeliverTo            string      `json:"deliver_to"`
		Quantity             string      `json:"quantity"`
		CompletedQuantity    string      `json:"completed_quantity"`
	    PlannedStartDate     string      `json:"planned_start_date"`
	    PlannedValidatedDate string      `json:"planned_validated_date"`
	    ActualStartDate      string      `json:"actual_start_date"`
	    ActualValidatedDate  string      `json:"actual_validated_date"`
	    Batch                string      `json:"batch"`
		Work              struct {
			WorkNo                   string      `json:"work_no"`
			Quantity                 string      `json:"quantity"`
			CompletedQuantity        string      `json:"completed_quantity"`
			ErroredQuantity          string      `json:"errored_quantity"`
			Component                string      `json:"component"`
			PlannedComponentQuantity string      `json:"planned_component_quantity"`
			PlannedStartDate         string      `json:"planned_start_date"`
			PlannedStartTime         string      `json:"planned_start_time"`
			PlannedValidatedDate     string      `json:"planned_validated_date"`
			PlannedValidatedTime     string      `json:"planned_validated_time"`
			ActualStartDate          string      `json:"actual_start_date"`
			ActualStartTime          string      `json:"actual_start_time"`
			ActualValidatedDate      string      `json:"actual_validated_date"`
			ActualValidatedTime      string      `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema                         string `json:"api_schema"`
	Accepter                        []string `json:"accepter"`
	MaterialCode                      string `json:"material_code"`
	Supplier                          string `json:"plant/supplier"`
	Stock                             string `json:"stock"`
	SalesOrderType                    string `json:"document_type"`
	MaintenanceNotificationNo         string `json:"document_no"`
	ScheduleLineDeliveryDate          string `json:"planned_date"`
	ValidatedDate                     string `json:"validated_date"`
    Deleted                           bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey           string `json:"connection_key"`
	Result                  bool   `json:"result"`
	RedisKey                string `json:"redis_key"`
	Filepath                string `json:"filepath"`
	MaintenanceNotification struct {
		MaintenanceNotification        string      `json:"MaintenanceNotification"`
		MaintNotifInternalID           string      `json:"MaintNotifInternalID"`
		NotificationText               string      `json:"NotificationText"`
		MaintPriority                  string      `json:"MaintPriority"`
		NotificationType               string      `json:"NotificationType"`
		NotifProcessingPhase           string      `json:"NotifProcessingPhase"`
		NotifProcessingPhaseDesc       string      `json:"NotifProcessingPhaseDesc"`
		MaintPriorityDesc              string      `json:"MaintPriorityDesc"`
		CreationDate                   string      `json:"CreationDate"`
		LastChangeTime                 string      `json:"LastChangeTime"`
		LastChangeDate                 string      `json:"LastChangeDate"`
		LastChangeDateTime             string      `json:"LastChangeDateTime"`
		CreationTime                   string      `json:"CreationTime"`
		ReportedByUser                 string      `json:"ReportedByUser"`
		ReporterFullName               string      `json:"ReporterFullName"`
		PersonResponsible              string      `json:"PersonResponsible"`
		MalfunctionEffect              string      `json:"MalfunctionEffect"`
		MalfunctionEffectText          string      `json:"MalfunctionEffectText"`
		MalfunctionStartDate           string      `json:"MalfunctionStartDate"`
		MalfunctionStartTime           string      `json:"MalfunctionStartTime"`
		MalfunctionEndDate             string      `json:"MalfunctionEndDate"`
		MalfunctionEndTime             string      `json:"MalfunctionEndTime"`
		MaintNotificationCatalog       string      `json:"MaintNotificationCatalog"`
		MaintNotificationCode          string      `json:"MaintNotificationCode"`
		MaintNotificationCodeGroup     string      `json:"MaintNotificationCodeGroup"`
		CatalogProfile                 string      `json:"CatalogProfile"`
		NotificationCreationDate       string      `json:"NotificationCreationDate"`
		NotificationCreationTime       string      `json:"NotificationCreationTime"`
		NotificationTimeZone           string      `json:"NotificationTimeZone"`
		RequiredStartDate              string      `json:"RequiredStartDate"`
		RequiredStartTime              string      `json:"RequiredStartTime"`
		RequiredEndDate                string      `json:"RequiredEndDate"`
		RequiredEndTime                string      `json:"RequiredEndTime"`
		LatestAcceptableCompletionDate string      `json:"LatestAcceptableCompletionDate"`
		MaintenanceObjectIsDown        bool        `json:"MaintenanceObjectIsDown"`
		MaintNotificationLongText      string      `json:"MaintNotificationLongText"`
		MaintNotifLongTextForEdit      string      `json:"MaintNotifLongTextForEdit"`
		TechnicalObject                string      `json:"TechnicalObject"`
		TechObjIsEquipOrFuncnlLoc      string      `json:"TechObjIsEquipOrFuncnlLoc"`
		TechnicalObjectLabel           string      `json:"TechnicalObjectLabel"`
		MaintenancePlanningPlant       string      `json:"MaintenancePlanningPlant"`
		MaintenancePlannerGroup        string      `json:"MaintenancePlannerGroup"`
		SuperiorTechnicalObject        string      `json:"SuperiorTechnicalObject"`
		SuperiorTechnicalObjectName    string      `json:"SuperiorTechnicalObjectName"`
		SuperiorObjIsEquipOrFuncnlLoc  string      `json:"SuperiorObjIsEquipOrFuncnlLoc"`
		SuperiorTechnicalObjectLabel   string      `json:"SuperiorTechnicalObjectLabel"`
		ManufacturerPartTypeName       string      `json:"ManufacturerPartTypeName"`
		TechObjIsEquipOrFuncnlLocDesc  string      `json:"TechObjIsEquipOrFuncnlLocDesc"`
		FunctionalLocation             string      `json:"FunctionalLocation"`
		FunctionalLocationLabelName    string      `json:"FunctionalLocationLabelName"`
		TechnicalObjectDescription     string      `json:"TechnicalObjectDescription"`
		AssetLocation                  string      `json:"AssetLocation"`
		LocationName                   string      `json:"LocationName"`
		BusinessArea                   string      `json:"BusinessArea"`
		CompanyCode                    string      `json:"CompanyCode"`
		TechnicalObjectCategory        string      `json:"TechnicalObjectCategory"`
		TechnicalObjectType            string      `json:"TechnicalObjectType"`
		MainWorkCenterPlant            string      `json:"MainWorkCenterPlant"`
		MainWorkCenter                 string      `json:"MainWorkCenter"`
		PlantName                      string      `json:"PlantName"`
		MaintenancePlannerGroupName    string      `json:"MaintenancePlannerGroupName"`
		MaintenancePlant               string      `json:"MaintenancePlant"`
		LocationDescription            string      `json:"LocationDescription"`
		MainWorkCenterText             string      `json:"MainWorkCenterText"`
		MainWorkCenterPlantName        string      `json:"MainWorkCenterPlantName"`
		MaintenancePlantName           string      `json:"MaintenancePlantName"`
		PlantSectionPersonRespName     string      `json:"PlantSectionPersonRespName"`
		PersonResponsibleName          string      `json:"PersonResponsibleName"`
		MaintenanceOrder               string      `json:"MaintenanceOrder"`
		MaintenanceOrderType           string      `json:"MaintenanceOrderType"`
		MaintenanceActivityType        string      `json:"MaintenanceActivityType"`
		MaintObjDowntimeDurationUnit   string      `json:"MaintObjDowntimeDurationUnit"`
		MaintObjectDowntimeDuration    string      `json:"MaintObjectDowntimeDuration"`
		MaintenancePlan                string      `json:"MaintenancePlan"`
		MaintenanceItem                string      `json:"MaintenanceItem"`
		TaskListGroup                  string      `json:"TaskListGroup"`
		TaskListGroupCounter           string      `json:"TaskListGroupCounter"`
		MaintenancePlanCallNumber      int         `json:"MaintenancePlanCallNumber"`
		MaintenanceTaskListType        string      `json:"MaintenanceTaskListType"`
		NotificationReferenceDate      string      `json:"NotificationReferenceDate"`
		NotificationReferenceTime      string      `json:"NotificationReferenceTime"`
		NotificationCompletionDate     string      `json:"NotificationCompletionDate"`
		CompletionTime                 string      `json:"CompletionTime"`
		AssetRoom                      string      `json:"AssetRoom"`
		MaintNotifExtReferenceNumber   string      `json:"MaintNotifExtReferenceNumber"`
		MaintNotifRejectionReasonCode  string      `json:"MaintNotifRejectionReasonCode"`
		MaintNotifRejectionRsnCodeTxt  string      `json:"MaintNotifRejectionRsnCodeTxt"`
		MaintNotifDetectionCatalog     string      `json:"MaintNotifDetectionCatalog"`
		MaintNotifDetectionCode        string      `json:"MaintNotifDetectionCode"`
		MaintNotifDetectionCodeText    string      `json:"MaintNotifDetectionCodeText"`
		MaintNotifDetectionCodeGroup   string      `json:"MaintNotifDetectionCodeGroup"`
		MaintNotifDetectionCodeGrpTxt  string      `json:"MaintNotifDetectionCodeGrpTxt"`
		MaintNotifProcessPhaseCode     string      `json:"MaintNotifProcessPhaseCode"`
		MaintNotifProcessSubPhaseCode  string      `json:"MaintNotifProcessSubPhaseCode"`
		MaintenanceNotificationItem    struct {
			MaintenanceNotificationItem   string      `json:"MaintenanceNotificationItem"`
			MaintNotifItemText            string      `json:"MaintNotifItemText"`
			MaintNotifDamageCodeGroup     string      `json:"MaintNotifDamageCodeGroup"`
			MaintNotifDamageCodeGroupName string      `json:"MaintNotifDamageCodeGroupName"`
			MaintNotificationDamageCode   string      `json:"MaintNotificationDamageCode"`
			MaintNotifDamageCodeName      string      `json:"MaintNotifDamageCodeName"`
			MaintNotifObjPrtCodeGroup     string      `json:"MaintNotifObjPrtCodeGroup"`
			MaintNotifObjPrtCodeGroupName string      `json:"MaintNotifObjPrtCodeGroupName"`
			MaintNotifObjPrtCode          string      `json:"MaintNotifObjPrtCode"`
			MaintNotifObjPrtCodeName      string      `json:"MaintNotifObjPrtCodeName"`
			IsDeleted                     bool        `json:"IsDeleted"`
			MaintenanceNotificationCause  struct {
				MaintenanceNotificationCause   string      `json:"MaintenanceNotificationCause"`
				MaintNotifCauseText            string      `json:"MaintNotifCauseText"`
				MaintNotifCauseCodeGroup       string      `json:"MaintNotifCauseCodeGroup"`
				MaintNotifCauseCodeGroupName   string      `json:"MaintNotifCauseCodeGroupName"`
				MaintNotificationCauseCode     string      `json:"MaintNotificationCauseCode"`
				MaintNotificationCauseCodeName string      `json:"MaintNotificationCauseCodeName"`
				MaintNotificationRootCause     string      `json:"MaintNotificationRootCause"`
				MaintNotificationRootCauseText string      `json:"MaintNotificationRootCauseText"`
				IsDeleted                      bool        `json:"IsDeleted"`
			} `json:"MaintenanceNotificationCause"`
		} `json:"MaintenanceNotificationItem"`
	} `json:"MaintenanceNotification"`
	APISchema                 string   `json:"api_schema"`
	Accepter                  []string `json:"accepter"`
	MaintenanceNotificationNo string   `json:"maintenance_notification"`
	Deleted                   bool     `json:"deleted"`
}
